name: Build Doric Token Creator

on:
  release:
    types: [created]

jobs:
  deploy_via_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_SSHKEY }}
          script: |
            cd /var/www/doric-token-creator
            git checkout master
            git pull
            npm install
            npm start
